#!/bin/sh
#
# ufetch-freebsd - tiny system info for freebsd

## INFO

# user is already defined
host="$(hostname)"
os="$(uname -sr)"
kernel="$(uname -iK)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages="$(pkg info | wc -l | sed -e 's/^[ \t]*//')"
shell="$(basename ${SHELL})"
if [ -z "${WM}" ]; then
	WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput md)"
black="$(tput AF 0)"
red="$(tput AF 1)"
green="$(tput AF 2)"
yellow="$(tput AF 3)"
blue="$(tput AF 4)"
magenta="$(tput AF 5)"
cyan="$(tput AF 6)"
white="$(tput AF 7)"
reset="$(tput me)"

# you can change these
lc="${reset}${bold}${red}"		# labels
nc="${reset}${bold}${red}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${red}"				# first color
c1="${reset}${bold}${red}"		# second color

## OUTPUT

cat <<EOF

${c0}   ${c1}/\\ ${c0}_____ ${c1}/\   ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}   ${c1}\_)     (_/   ${lc}OS:        ${ic}${os}${reset}
${c0}   /         \   ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}  |           |  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}  |           |  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}   \         /   ${lc}SHELL:     ${ic}${shell}${reset}
${c0}    --_____--    ${lc}WM:        ${ic}${WM}${reset}

EOF
