#!/bin/sh
#
# ufetch-fedora - tiny system info for fedora

## INFO

# user is already defined
host="$(hostname)"
os="$(cat /etc/fedora-release)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(yum list installed | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${blue}"		# labels
nc="${reset}${bold}${blue}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${white}"			# first color

## OUTPUT

cat <<EOF
${c0}       _____
${c0}      /   __/  ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}     |  /      ${lc}OS:        ${ic}${os}${reset}
${c0}    _|  |_     ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}   |_    _|    ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}     |  |      ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}   __/  |      ${lc}SHELL:     ${ic}${shell}${reset}
${c0}  /____/       ${lc}${envtype}:        ${ic}${WM}${reset}

EOF
