#!/bin/sh
#
# ufetch-manjaro - tiny system info for manjaro

## INFO

# user is already defined
host="$(hostname)"
os='Manjaro'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename ${SHELL})"
if [ -z "${WM}" ]; then
	WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${green}"	# labels
nc="${reset}${bold}${green}"	# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${green}"			# first color

## OUTPUT

cat <<EOF

${c0}  █████████ ████  ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}  █████████ ████  ${lc}OS:        ${ic}${os}${reset}
${c0}  ████      ████  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}  ████ ████ ████  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}  ████ ████ ████  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}  ████ ████ ████  ${lc}SHELL:     ${ic}${shell}${reset}
${c0}  ████ ████ ████  ${lc}WM:        ${ic}${WM}${reset}

EOF
