#!/bin/sh
#
# ufetch-crux - tiny system info for crux
#

## INFO

# user is already defined
hostname="$(hostname)"
os="$(crux)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pkginfo -i | wc -l)"
shell="$(basename ${SHELL})"
if [ -z "${WM}" ]; then
	WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
fi

## DEFINE COLORS

# probably don't change these
bc="$(tput bold)"		# bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"		# reset

# you can change these
lc="${rc}${bc}${c6}"	# labels
nc="${rc}${bc}${c6}"	# user and hostname
ic="${rc}${bc}${c7}"	# info
pc="${rc}${c6}"			# penguin

## OUTPUT

cat <<EOF

${pc}      ___     ${nc}${USER}${ic}@${nc}${hostname}${rc}
${pc}     (${c7}.· ${pc}|    ${lc}OS:        ${ic}${os}${rc}
${pc}     (${c3}<> ${pc}|    ${lc}KERNEL:    ${ic}${kernel}${rc}
${pc}    / ${c7}__  ${pc}\\   ${lc}UPTIME:    ${ic}${uptime}${rc}
${pc}   ( ${c7}/  \\ ${pc}/|  ${lc}PACKAGES:  ${ic}${packages}${rc}
${c3}  _${pc}/\\ ${c7}__)${pc}/${c3}_${pc})  ${lc}SHELL:     ${ic}${shell}${rc}
${c3}  \/${pc}-____${c3}\/   ${lc}WM:        ${ic}${WM}${rc}

EOF
