#!/bin/sh
#
# ufetch-freebsd - tiny system info for freebsd

## INFO

# user is already defined
host="$(hostname)"
os="$(uname -sr)"
kernel="$(uname -iK)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages="$(pkg info | wc -l | sed -e 's/^[ \t]*//')"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput md)"
black="$(tput AF 0)"
red="$(tput AF 1)"
green="$(tput AF 2)"
yellow="$(tput AF 3)"
blue="$(tput AF 4)"
magenta="$(tput AF 5)"
cyan="$(tput AF 6)"
white="$(tput AF 7)"
reset="$(tput me)"

# you can change these
lc="${reset}${bold}${red}"		# labels
nc="${reset}${bold}${red}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${bold}${red}"		# first color
c1="${reset}${red}"				# second color

## OUTPUT

cat <<EOF

${c0}   _  ${c1}_____  ${c0}_   ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}  / \\\`     \`/ \\  ${lc}OS:        ${ic}${os}${reset}
${c0}  \/       (__/  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c1}  |           |  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c1}  |           |  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c1}   \         /   ${lc}SHELL:     ${ic}${shell}${reset}
${c1}    \`-_____-\`    ${lc}${envtype}:        ${ic}${WM}${reset}

EOF
