#!/bin/bash

## ufetch - tiny system info

## INFO
# edit if customization is needed

# user is already defined
# hostname is already defined
OS="CRUX 3.1"
KERNEL=$(uname -rs)
PACKAGES=$(pkginfo -i | wc -l)
# shell is already defined
WM=$(tail -n 1 "$HOME/.xinitrc" | cut -d " " -f2)
FONT="Profont 9"
WEBSITE="driedonionsoup.com"

## DEFINE COLORS

rc=$(tput sgr0)		# reset
c0=$(tput setaf 0)	# black
c1=$(tput setaf 1)	# red
c2=$(tput setaf 2)	# green
c3=$(tput setaf 3)	# yellow
c4=$(tput setaf 4)	# blue
c5=$(tput setaf 5)	# magenta
c6=$(tput setaf 6)	# cyan
c7=$(tput setaf 7)	# white
bc=$(tput bold)		# bold

## OUTPUT
# todo: make good

cat <<EOF

      ${c6}___${rc}     ${c6}${bc}${USER}${c7}@${c6}${HOSTNAME}${rc}
     ${c6}(${c7}.·${rc} ${c6}|${rc}    ${c6}${bc}OS:${rc}       ${c7}${OS}${rc}
     ${c6}(${c3}<>${rc} ${c6}|${rc}    ${c6}${bc}KERNEL:${rc}   ${c7}${KERNEL}${rc}
    ${c6}/${rc} ${c7}__${c6}${rc}  ${c6}\\${rc}   ${c6}${bc}PACKAGES:${rc} ${c7}${PACKAGES}${rc}
   ${c6}(${c7}${rc} ${c7}/${rc}  ${c7}\\${rc} ${c6}/|${rc}  ${c6}${bc}SHELL:${rc}    ${c7}${SHELL}${rc}
  ${c3}_${c6}/\\${rc} ${c7}__)${c6}/${c3}_${c6})${rc}  ${c6}${bc}WM:${rc}       ${c7}${WM}${rc}
  ${c3}\/${c6}-____${c3}\/${rc}   ${c6}${bc}WEBSITE:${rc}  ${c7}${WEBSITE}${rc}

EOF
