#!/bin/sh
#
# ufetch-openbsd - tiny system info for openbsd

## INFO

# user is already defined
host="$(hostname)"
os="$(uname -sr)"
kernel="$(uname -v)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages="$(pkg_info -A | wc -l | sed -e 's/^[ \t]*//')"
shell="$(basename ${SHELL})"
if [ -z "${WM}" ]; then
	WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${yellow}"	# labels
nc="${reset}${bold}${yellow}"	# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${yellow}"			# first color
c1="${reset}${white}"			# second color
c2="${reset}${bold}${yellow}"	# third color


## OUTPUT

cat <<EOF

${c0}       _____      ${nc}${USER}${ic}@${nc}${host}${rc}
${c0}     \-     -/    ${lc}OS:        ${ic}${os}${rc}
${c0}  \_/         \   ${lc}KERNEL:    ${ic}${kernel}${rc}
${c0}  |        ${c1}O O ${c0}|  ${lc}UPTIME:    ${ic}${uptime}${rc}
${c0}  |_  ${c2}<   ${c0})  ${c2}3 ${c0})  ${lc}PACKAGES:  ${ic}${packages}${rc}
${c0}  / \         /   ${lc}SHELL:     ${ic}${shell}${rc}
${c0}     /-_____-\    ${lc}WM:        ${ic}${WM}${rc}

EOF
