#!/bin/sh
#
# ufetch-macos - tiny system info for macos

## INFO

# user is already defined
host="$(hostname)"
os="$(sw_vers -productName) $(sw_vers -productVersion)"
kernel="$(uname -sr)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
if command -v pkgin &> /dev/null; then
	packages="$(pkgin list | wc -l)"
elif command -v brew &> /dev/null; then
	brew_packages="$(brew list | wc -l)"
	cask_packages="$(brew cask list 2> /dev/null | wc -l)"
	packages="$(( ${brew_packages} + ${cask_packages} ))"
elif command -v port &> /dev/null; then
	packages="$(port installed | wc -l)"
else
	packages='no package manager'
fi
packages="$(echo ${packages} | sed -e 's/^[ /t]*//')"
shell="$(basename ${SHELL})"
if [ -z "${WM}" ]; then
	WM='Quartz Compositor'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${blue}"		# labels
nc="${reset}${bold}${blue}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${green}"			# first color
c1="${reset}${yellow}"			# second color
c2="${reset}${red}"				# third color
c3="${reset}${magenta}"			# fourth color
c4="${reset}${cyan}"			# fifth color

## OUTPUT

cat <<EOF

${c0}         .:'    ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}      _ :'_     ${lc}OS:        ${ic}${os}${reset}
${c1}   .'\`_\`-'_\`\`.  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c2}  :________.-'  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c2}  :_______:     ${lc}PACKAGES:  ${ic}${packages}${reset}
${c3}   :_______\`-;  ${lc}SHELL:     ${ic}${shell}${reset}
${c4}    \`._.-._.'   ${lc}WM:        ${ic}${WM}${reset}

EOF
