#!/bin/sh
#
# ufetch-void - tiny system info for void

## INFO

# user is already defined
host="$(hostname)"
os='Void Linux'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(xbps-query -l | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${green}"	# labels
nc="${reset}${bold}${green}"	# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${bold}${green}"	# first color
c1="${reset}${green}"			# second color

## OUTPUT

cat <<EOF

${c0}      _______      ${nc}${USER}${ic}@${nc}${host}${reset}
${c1}      ${c0}\_____ \`-    ${lc}OS:        ${ic}${os}${reset}
${c1}   /\   ${c0}___ \`- \   ${lc}KERNEL:    ${ic}${kernel}${reset}
${c1}  | |  ${c0}/   \  | |  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c1}  | |  ${c0}\___/  | |  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c1}   \ \`-_____  ${c0}\/   ${lc}SHELL:     ${ic}${shell}${reset}
${c1}    \`-______\      ${lc}${envtype}:        ${ic}${WM}${reset}

EOF
