#!/bin/bash

## ufetch - tiny system info

## INFO
# edit if customization is needed

# user is already defined
# hostname is already defined
OS="CRUX 3.1"
KERNEL=$(uname -rs)
PACKAGES=$(pkginfo -i | wc -l)
# shell is already defined
WM="spectrwm"
FONT="Profont 9"
WEBSITE="driedonionsoup.com"

## DEFINE COLORS
# probably don't change these

rc=$(tput sgr0)		# reset
c0=$(tput setaf 0)	# black
c1=$(tput setaf 1)	# red
c2=$(tput setaf 2)	# green
c3=$(tput setaf 3)	# yellow
c4=$(tput setaf 4)	# blue
c5=$(tput setaf 5)	# magenta
c6=$(tput setaf 6)	# cyan
c7=$(tput setaf 7)	# white
bc=$(tput bold)		# bold

## RESIZE WINDOW
# ripped from onodera, edit window height and width if desired

if [[ -n "$DISPLAY" ]]; then
	wmctrl -r :ACTIVE: -e "0,-1,-1,318,156"
fi

## OUTPUT
# good luck

printf "\n"
printf "%s" "$c6      ___    $rc"
printf "%s\n" "$c6$bc $USER$c7@$c6$HOSTNAME$rc"
printf "%s" "$c6     ($c7.. $c6|   $rc"
printf "%s\n" "$c6$bc OS:       $c7$OS$rc"
printf "%s" "$c6     ($c3<> $c6|   $rc"
printf "%s\n" "$c6$bc KERNEL:   $c7$KERNEL$rc"
printf "%s" "$c6    /$c7 __  $c6\  $rc"
printf "%s\n" "$c6$bc PACKAGES: $c7$PACKAGES$rc"
printf "%s" "$c6   ( $c7/  \ $c6/| $rc"
printf "%s\n" "$c6$bc SHELL:    $c7$SHELL$rc"
printf "%s" "$c3  _$c6/\\$c7 __)$c6/$c3"
printf "%s" "_$c6) $rc"
printf "%s\n" "$c6$bc WM:       $c7$WM$rc"
printf "%s" " $c3 \/$c6-____$c3\/  $rc"
printf "%s\n" "$c6$bc WEBSITE:  $c7$WEBSITE$rc"
printf "\n"
